# Generated by Django 4.2.17 on 2025-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
