# Generated by Django 4.2.17 on 2025-02-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp1", "0002_simpleuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mushroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("mycelery", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Snippet",
        ),
        migrations.AlterModelOptions(
            name="simpleuser",
            options={"verbose_name": "用户管理", "verbose_name_plural": "用户管理"},
        ),
        migrations.AddField(
            model_name="simpleuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
